23/04/2017 00:40:12 | InsertUpdateUser | Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

23/04/2017 00:42:21 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 00:54:41 | InsertUpdateUser | Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

23/04/2017 00:59:03 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 01:09:02 | InsertUpdateUser | The operation cannot be completed because the DbContext has been disposed.

23/04/2017 01:13:01 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 01:18:02 | InsertUpdateUser | ok

23/04/2017 02:22:22 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 02:27:40 | InsertUpdateUser | ok

23/04/2017 02:28:34 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 16:49:49 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 16:51:22 | InsertUpdateUser | ok

23/04/2017 16:53:09 | InsertUpdateUser | ok

23/04/2017 17:58:35 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 17:59:36 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 20:19:53 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 20:24:27 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 20:26:18 | LogException | L'instruction INSERT est en conflit avec la contrainte FOREIGN KEY "FK_CENTREPROFIL_ADMUTILISATEUR". Le conflit s'est produit dans la base de données "GALADB", table "dbo.ADMUTILISATEUR", column 'PK_ID'.
L'instruction a été arrêtée.

23/04/2017 20:26:18 | LogException | Une erreur s'est produite lors de la mise à jour des entrées. Pour plus d'informations, consultez l'exception interne.

23/04/2017 20:26:18 | InsertUpdateUser | Une erreur s'est produite lors de la mise à jour des entrées. Pour plus d'informations, consultez l'exception interne.

23/04/2017 20:30:53 | LogException | L'instruction INSERT est en conflit avec la contrainte FOREIGN KEY "FK_CENTREPROFIL_ADMUTILISATEUR". Le conflit s'est produit dans la base de données "GALADB", table "dbo.ADMUTILISATEUR", column 'PK_ID'.
L'instruction a été arrêtée.

23/04/2017 20:30:53 | LogException | Une erreur s'est produite lors de la mise à jour des entrées. Pour plus d'informations, consultez l'exception interne.

23/04/2017 20:30:53 | InsertUpdateUser | Une erreur s'est produite lors de la mise à jour des entrées. Pour plus d'informations, consultez l'exception interne.

23/04/2017 20:32:40 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 20:38:43 | LogException | L'instruction INSERT est en conflit avec la contrainte FOREIGN KEY "FK_CENTREPROFIL_ADMUTILISATEUR". Le conflit s'est produit dans la base de données "GALADB", table "dbo.ADMUTILISATEUR", column 'PK_ID'.
L'instruction a été arrêtée.

23/04/2017 20:38:43 | LogException | Une erreur s'est produite lors de la mise à jour des entrées. Pour plus d'informations, consultez l'exception interne.

23/04/2017 20:38:43 | InsertUpdateUser | Une erreur s'est produite lors de la mise à jour des entrées. Pour plus d'informations, consultez l'exception interne.

23/04/2017 20:41:54 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 20:47:11 | InsertUpdateUser | The operation cannot be completed because the DbContext has been disposed.

23/04/2017 20:51:46 | SyncInvokeRetourneListeAllUser | ok

23/04/2017 20:54:05 | InsertUpdateUser | ok

23/04/2017 22:40:38 | LogException | Le chemin réseau n’a pas été trouvé

23/04/2017 22:40:38 | LogException | Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

23/04/2017 22:40:38 | RetourneListePoste | Échec du fournisseur sous-jacent sur Open.

23/04/2017 22:45:28 | LogException | Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

23/04/2017 22:45:28 | RetourneListePoste | Échec du fournisseur sous-jacent sur Open.

